### ISSUE TITLE
Doesn't support Minus "-" character

### ISSUE THREAD

**Issue by losPrellos** [nicolonsky/IntuneDriveMapping#10]
Hi,
very cool tool (y)
I have the problem that the minus character "-" on the UNC Path is not accepted.
UNC: \\file-server\file-share\ = "Valid UNC path required"
Can you fix that please?

**Comment by nicolonsky** [comment]
Thanks for your feedback. Just fixed this: https://github.com/nicolonsky/IntuneDriveMapping/commit/fa8033f491757c5688cf04516bbd44fe9339cfe7. Happy to hear your feedback.
