### ISSUE TITLE
Intune Powershell Script Execution Reporting as "Failed/Error"

### ISSUE THREAD

**Issue by CJHarms** [nicolonsky/IntuneDriveMapping#12]
Hi there,

I have a small Bug Report regarding the Execution Reporting of the Powershell Script in the Intune Web UI. The Powershell Script is executed successfully on the Clients and for te Users and all the needed Drives are mapped (fantastic work on the Script by the way!) but in the Intune Web UI all the Devices and Users are getting Reported as Error/Failed.

I'm guessing that somehow the Exit Codes from the Script are not the ones Intune expects them to be or they need to be implemented. Would be great if you could fix/implement this when you got the time.

Thanks in advance and thanks for the fantastic Script!

**Comment by CJHarms** [comment]
Almost forgot: If you need more Information or Logs for Troubleshooting or something else feel free to contact me and I'll try to help where I can.

**Comment by nicolonsky** [comment]
Hi @CJHarms sorry for the late reply but I've been on vacation. Could you try to replace line #150 in your script with the following: ```Get-ChildItem -Path HKCU:\Network -ErrorAction SilentlyContinue | ForEach-Object {New-ItemProperty -Name ConnectionType -Value 1 -Path $_.PSPath -Force -ErrorAction SilentlyContinue}``` and see if it helps?

**Comment by CJHarms** [comment]
Hi @nicolonsky took me also some time to test your proposed Fix but I can report that it fixed the Issue for me.

I see you already commited the new Code in your Commit a5baa4fa06da8c28d99a6a964eb485e4f912aac8 

Thanks for the quick help! Keep up the good work and stay safe and healthy.

**Comment by nicolonsky** [comment]
@CJHarms thanks for the feedback. Yes changes are already pushed to code / the online version of the tool. Cheers and stay save & healthy too.
