### ISSUE TITLE
Variable on the path 

### ISSUE THREAD

**Issue by edisontea** [nicolonsky/IntuneDriveMapping#14]
Hi Nicolonsky, Great work on your IntuneDriveMapping generator! We want to use your script to map drive to user's home folder. Is it possible for your script to accept a variable on the UNC path ie. - \\server1\users\%username%? It doesn't seem to work, specific path works. Any suggestions? Thanks~

**Comment by edisontea** [comment]
Correction - \\server1\users\%username%

**Comment by Bubbahewitt** [comment]
Same issue, "WARNING: The property 'Name' cannot be found on this object. Verify that the property exists and can be set."

**Comment by nicolonsky** [comment]
Simply use `\\intra.tech.nicolonsky.ch\home\$env:username` because it's PowerShell.
