### ISSUE TITLE
Webpage not available for creating drive mappings

### ISSUE THREAD

**Issue by JacquesRodrigues** [nicolonsky/IntuneDriveMapping#22]
Hi,

We were looking forward to using your tool, but at the moment it seems to be offline.
Webpage says: 

Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here. For further troubleshooting tools and recommendations, please visit Azure Portal.

Will this be sorted or have you guys stopped developing?

**Comment by nicolonsky** [comment]
Hi @JacquesRodrigues this is sorted. My Azure subscription runs out of available subscription benefits from time to time and this pauses the application. The tool is maintained and developed by myself and the hosting is covered by my personal subscription benefits and donations I occasionally receive.
