### ISSUE TITLE
UNC paths with spaces 

### ISSUE THREAD

**Issue by dreigo42** [nicolonsky/IntuneDriveMapping#28]
The site does not accept unc paths with spaces. Not sure if the script could be modified manually. Says "Valid UNC Path Required"

Example: \\YourDomain\Network\Share Name

Otherwise, this is excellent work.

**Comment by nodrogneirbo** [comment]
I'm struggling to get UNC paths with spaces working. Did you find a workaround @dreigo42

**Comment by dreigo42** [comment]
Unfortunately not. Time constraints being what they are and the fact that I changed employers to one not using Intune meant that I never had a chance to look into it much.

Sorry.

**Comment by nicolonsky** [comment]
https://github.com/nicolonsky/IntuneDriveMapping/pull/37
