### ISSUE TITLE
Use system variables as drive label?

### ISSUE THREAD

**Issue by elephantgrenades** [nicolonsky/IntuneDriveMapping#34]
Our org uses the $env:USERNAME variable to map our user folders. Looking at the script, I can't see a way that doesn't treat that as a string. Is there a alternative way to map the drive with a variable name?

**Comment by nicolonsky** [comment]
https://github.com/nicolonsky/IntuneDriveMapping/wiki#adding-network-drive-mapping-entries


On 19 Aug 2021, at 18:46, elephantgrenades ***@***.***> wrote:

﻿

Our org uses the $env:USERNAME variable to map our user folders. Looking at the script, I can't see a way that doesn't treat that as a string. Is there a alternative way to map the drive with a variable name?

**Comment by elephantgrenades** [comment]
Apologies. I should have used clearer language. I'm looking for a way to use a variable as the label display name. So, H: maps as $env:USERNAME. If Joe Smith's AD account was jsmith, then H: would map as jsmith in WIndows Explorer.

**Display Name - reflects the name displayed in windows explorer.**

Is that possible?

**Comment by elephantgrenades** [comment]
Bump. Anyone have an idea if what I'm asking is possible?

**Comment by elephantgrenades** [comment]
I finally had time to look at this more in depth and found that if the **Display Name** is left blank or labeled as _null_ the drive maps with the name of the logged in user. Thanks.
