### ISSUE TITLE
Allow updating script in editor

### ISSUE THREAD

**Issue by jfundingsrud** [nicolonsky/IntuneDriveMapping#35]
Not an issue as much as a feature request.
I love the fact that you can upload an xml to convert a gpo. Would it be possible to allow upload of a script for editing it. Or possibly download a updated xml alongside the script for the possibility of future uploading and editing?
Yes, I could fairly easilly edit the scipt directly, but I oversee a team of brilliant maintenance people that are great at point and click admining, but useless at reading and implementing code... :)

**Comment by nicolonsky** [comment]
This should already be possible to upload a created *.ps1 script

**Comment by jfundingsrud** [comment]
Wow, thanks for the quick reply! 

Perhaps adjust the wording slightly on bullet point 0 in the user guide? :) Might be me being the useless one in this case though :)
