### ISSUE TITLE
Doesn't support "_" character

### ISSUE THREAD

**Issue by phillip-white-jarden** [nicolonsky/IntuneDriveMapping#7]
Hey mate, nice work on this, cool stuff.

I've seen the manual mapping generator doesn't support he underline character `_`. Any chance you can include this?

**Comment by nicolonsky** [comment]
Hi @phillip-white-jarden  sorry for the late response but this should be fixed now .[https://github.com/nicolonsky/IntuneDriveMapping/commit/9601e618c5593f9fa771f161b2d4983afaa4d617](https://github.com/nicolonsky/IntuneDriveMapping/commit/9601e618c5593f9fa771f161b2d4983afaa4d617)
